const transcripts = [
  `Amanda: Welcome to Spirits Podcast, a boozy dive into mythology, legends and folklore. Every week we pour a drink and learn about a new story from around the world. I'm Amanda.
  Julia: I'm Julia.
  Amanda: This is episode 164, Vampires and Only Lovers Left Alive. It's a myth movie night.
  Julia: Myth movie night.
  Amanda: Listen, pop that popcorn, put whatever wild topping you want on it. I like some nutritional yeast. Yes, I was a vegan for six years. Yes, I'm super into yeast.
  Julia: Love of yeast. Maybe you want to put a little bit of like, I don't know, dry blood powder or something like that because we are talking about vampires.
  Amanda: Hell yeah, we are. This might be one of our top five most requested topics, and what better way to get into vampire history and lore and other media adaptations. Then a movie I referenced far more than I think anybody else ever has, Only Lovers Left Alive.
  Julia: That is true. That is absolutely true. I haven't seen this movie before now. Amanda, it was a good choice. I think it's up there with my favorite vampire movie, my favorite being, Let the right one in.
  Amanda: Incredible. I am so glad to hear it. Do you know who I would let in every time if they knocked on my door?
  Julia: Sure, tell me.
  Amanda: Our newest patrons Bee and Deborah, welcome. Thank you for joining. You joined the ranks of all of our patrons, including our distinguished supporting producer level patrons, Philip, Megan, Debra, Molly, Skyla, Samantha, Sammy, Neil, Jessica, and feel fresh.
  Julia: Yeah, and our legend level patrons, Brittany, Josie ...
  Amanda: Whom I sent the cutest pins this month. Oh my goodness, I really wanted to keep some for myself, but I got one for you, Julia.
  Julia: So, kind. Thank you.
  Amanda: Well, they are Brittany, Josie, Kylie, Charlotte, Kylo the Husky, Morgan, BMEupscotty, Audra, Chris, Mark, Mr. Folk, Sarah and Jack Murray. Love them, and Julie, what would you be sharing with the legend level patrons if they came over to our house while we recorded this episode?
  Julia: Well, I wanted to pick something that felt like genuinely old to go with the fact that we have pretty ancient vampires in this film. But the concept of the cocktail is we know it only dates to the 1860s with like the more popular ones that we think of today coming in around the prohibition era in the 1920s. For this one, I chose to make an aviation, so it has that red purple tinge to it. It's got gin, Maraschino liqueur, Crème de violette and lemon juice.
  Amanda: Delicious.
  Julia: Little cute, little classy and a little bit vampirey.
  Amanda: Well, I actually wanted to make a themed recommendation this week as well.
  Julia: Tell me, tell me what you got.`,
  `Amanda: I recently tore through this memoir in about 12 hours, Blood, Butter and Bones by Gabrielle Hamilton. Hamilton is a chef of the restaurant Prune here in New York City, which is a really delicious like French inspired bistro basically. I had heard of her as just a figure in the food world. She's not a TV chef and not a celebrity chef in that way, but she's hugely influential. She was cited in another book I recently read called Burn the Ice, a history of the renaissance of restaurants and cocktails in America. So, when you mentioned the prohibition era cocktails, idea of the speakeasy, a bunch of the bars that we frequent here in New York City were mentioned in this book, but then someone was like, "Oh yeah, Gabrielle Hamilton mentored me and I would not be a chef without her."
  Amanda: I was like, "I need to know who this person is." So, she wrote the memoir Blood, Butter and Bones about her upbringing, her inspiration, why she loves food, how she started a restaurant. It was just one of the best written memoirs I've ever read, period. I'm left with so many sharp images from reading it and like smells and tastes almost the way she describes the food. If you're into more history side of things and what makes American dining so interesting, and is it going to end? The oral history of the last 20 years of food and drink in the US as Burn the Ice and then Gabrielle Hamilton's memoir is Blood, Butter and Bones.
  Julia: Wow. Dang, great recommendation. Love it.
  Amanda: Thanks. He did good
  Julia: In terms of recommending people to do and see things, Amanda, I hear that we are going to be in a couple of different places soon.
  Amanda: We sure will. We would love, please, to see your beautiful faces in LA on February 15th. Those are limited number of tickets, so if you can come see it, please bring a friend, bring a buddy, bring a date, bring that neighbor who you know has some cool pins and would probably love spirits as well. The tickets are at multitude.productions/live, as well as tickets to our upcoming double bill with Join the Party on February 27th in Austin and our upcoming live show in a Museum in Boston on May 6th.
  Julia: I'm so excited to just perform in a Museum. LA and Austin, I'm also very excited to perform because I haven't performed there yet, but also Boston Museum.
  Amanda: I know. It's going to be incredible. Most urgently is we definitely want to see your faces in LA, so if you live in California or the greater LA area or you're coming into town for a podcast movement, which we'll also be giving some talks at, come on over and join us.
  Julia: Yeah, it's going to be a blast. Also, totally said that memoir title wrong. It's Blood, Bones and Butter, but google the three words, you'll get there.
  Amanda: Yeah, eventually.
  Julia: Well, without further ado, please enjoy episode I64, Vampires and Only Lovers Left Alive.
  Julia: Amanda, I know that this is your favorite vampire film of all time.
  Amanda: It is.
  Julia: Which I think means it's the perfect time for you to do our two-minute summary.
  Amanda: I feel like I always do them. Is that true?
  Julia: No, I did the last one. It was the ghost of Christmas. Spirit of Christmas.
  Amanda: True, that's right.
  Julia: I got my timer. Hold on.
  Amanda: Hold on. I'm going to start one as well. I am also equipped with the knowledge. All right, so if you don't want to be spoiled for this movie, please skip forward exactly two minutes and we will be all done with our summary.
  Julia: Ready?
  Amanda: So go. Only lovers Left Alive. We have Adam and Eve. Just super on the nose here. Lots of references. There are two vampires who are extremely old, Adam, Tom Hiddleston, lives in Detroit where he is a famous musician but is very like secluded and doesn't want people to know who he is. Then Tilda Swinton is Eve and lives in Tangier where she hangs out with Christopher Marlow who apparently faked his own death and also wrote all of Shakespeare's plays. Adam is feeling rough. He got like a wooden bullet and is contemplating suicide. Tilda Swinton is hanging out in Tangier but realizes that he is in a tough place so she goes to Detroit to comfort him.
  Amanda: However, they're in a situation where they're comforting each other, figuring it out. It's disrupted when Eve's younger sister Ava comes in from Los Angeles. She is just like off the fan. She gives Ian this flask that she secretly filled with blood, this cute guy, Ian, and then Ava accidentally kills him by drinking too much of his blood. Adam kicks her out, they sort of need to leave. They go back to Tangier, they have to carry only the things that they have with them on the plane, and then they visit Marlow being like, "Hey, we are desperately hungry." Adam can no longer go to his hookup at a local hospital to get blood. They find out though that when they get to Marlow's house that he had died from accidentally drinking poisoned blood, and that was so brutal and sad.
  Amanda: The two of them are just staggering through the streets, they're so hungry and they see a lovely couple who no doubt reminds them of themselves back when they were first made. Then the movie closes with the two of them, going toward the couple to drink their blood and turn them into vampires.`,
  `Julia: Wow. Under two minutes. I'm very impressed.
  Amanda: I did make some notes in case I had to do this.
  Julia: Okay, good. That was smart. I'm very impressed regardless.
  Amanda: Thank you. More than the plot of the movie, there are just so many themes that I really love. There are a ton of artistic references to different, both the portraits in Adam's house. There are the names that people take on and they all referenced great art throughout the ages. The two of them talk about art a lot, listening to music, looking at art, talking about Mary Shelley and other people that they have met in apparently drank from, or been lovers with over the years. More than anything, I have a sense of boredom and the sense of when you're alive for that long, how do you maintain momentum and growth? And is just like hedonistic pleasures like sex and art enough to sustain a life? And what do you do when you kind of want more or different?
  Julia: Yeah, and I feel like those are topics that a lot of vampire media tends to focus on and really examine because in a lot of ways the vampires, we know it now through movies and books and TV, are these immortal beings that can live forever so long as they're sustained. So, of course they have experienced culture in ways that our short lives cannot, and also have to deal with these everlasting lives, which probably can lead to boredom and existential crisis.
  Amanda: Yeah. Also, as I was doing some research on more, the media side of vampires, like adaptations of different vampire works and just depictions of them throughout time, I did realize how cinematic our idea of the vampire is and the vampire myth. These are Easty beings that we want to look at versus something like a werewolf where often a movie will cut away, or they'll hint at it and then you see a more gruesome depiction of a creature, versus vampires who are often beautiful, often rich and a lot of the adaptations that I'm going to walk you through, they are the height of power, or they're like a thriving underground society. There's just resources there that a lot of othered groups in mythology and folklore media don't get to have.
  Julia: Yeah, absolutely. Would you like to start with a historical run through of different vampires across the world or would you prefer to talk about the media as we understand it and then explore where those roots came from?
  Amanda: I would love to hear your part first because I think that'll let us pluck out different references to vampire lores around the world and the versions that I have found.
  Julia: Yeah. Feel free to interject when you hear something that you think is a reference to what the media has portrayed vampires as. I would happy to talk about that.
  Amanda: Well, I will. Thank you.
  Julia: Awesome. So, I guess I'll start with the fact that I was doing my research and a lot of internet research about vampires online is sketchy at best because I feel as though media portrayals of things have really influenced the way that we see the historical vampire. For example, a lot of sources online say that the term vampire first appeared in English in 1734 in the poem, The Vampire of the Fins, but I can't find a copy of that online or made reference to in anything other than the fact that that is the first appearance of the word. That's going to give you an idea of what researching vampires is like unless you're very specifically looking at a type from a certain region.
  Amanda: Yeah.`,
  `Julia: One of the wonderful facts about vampires is the fact that they occur across the world and therefore they vary in terms of how we identify them. Some of the oldest vampires or vampire equivalents, because as you'll see, the idea of the vampire is just they either suck blood or life force. That's what we consider a vampire, not necessarily like, oh they live forever or they turn into bats or other animals and etc. some of the oldest ones date back to ancient Sumerian and Babylonian myths from around 4,000 BCE. One example being the Ekimmu or Edimmu, meaning one who is snatched away and that is a spirit of a person who was not buried properly and then returns as a vengeful spirit and would suck the life force out of the living.
  Julia: The Babylonians also believed in Lilitu, which is similarly associated with the Hebrew story of Lilith, who is the first wife of Adam and Eve, which made me giggle thinking about it while watching the film. Lilith, according to stories, refuse to be subservient to her husband Adam, and then was banished from Eden and became queen of the demons. She and her daughters, which are known as Lilu, would prey on young babies, new mothers and young men subsisting on their blood. The Sumerians had a different version of Lilith where she was said to be either an infertile, beautiful woman who would choose a lover and then feed off him and never let him go. Or alternatively, she was said to be a bird footed demonic woman who would attack at night and again, would feed on the blood of babies and their mothers.
  Amanda: Reminds me of the Aswang a little bit too.
  Julia: Yes. We'll get to the Aswang and various forms of it later on. Don't worry. I got you.
  Amanda: Okay. Cool.
  Julia: Speaking of Jewish traditions and Lilith, there was also another term called the Alukah, which was used to mean horse-leech, which quite literally could mean a type of leech that would feed off the throats of animals, but it was alternatively used for a blood lusting creature or a vampire. Other interpretations said that it was a living human who could change their shape into a Wolf or could fly by releasing its long hair, the hair would be tied up and then in releasing it, they could fly, which is extremely cool imagery. I really, really like that.
  Amanda: Oh yeah.
  Julia: It was said that the person would die if they were prevented from drinking blood for an extended period of time, which is very similar to modern vampire myth as we know it today. That, instead of being demonic in life, they only thirsted for blood, but if they died because they hadn't been drinking blood, they would then turn into a demon in death.
  Amanda: Oh no.
  Julia: Yeah. I like that imagery, the idea that a person has to continue feeding, and if they aren't able to, that's when they become demonic.
  Amanda: Yeah. It's like an even more tragic version.
  Julia: Yeah. Seriously. In order to prevent this from happening though, you could bury the person and then fill their mouth with dirt and that would stop them from transforming into a demon.
  Amanda: Wow. There's a lot of like burial and grave dirt associated with these myths.
  Julia: Yeah, for sure. That's not just middle Eastern and Western tradition too. I'll talk a little bit more about another version of that where its like burial places are reason that vampires can be created.`,
  `Amanda: Cool. Well I guess part of that too, it's coming to mind now, and I'm sure we'll see it traced in other stories, but the main appeal of death is that it is the end of like our needs and our mortal suffering and the daily relentless need to meet our body's requirements, and the idea that you could spend death even more insatiable for something that's hard to get, or in the previous example that you just listed, they're damned if you do and damned if you don't, is I think so like poetic but also resonant because death is supposed to be like an absence of need and pain, and here it's a different kind of it.
  Julia: Yeah. I think that also plays on the idea that despite the fact that in a lot of traditions death is the end of suffering, people are still afraid of the end of that because it's the only existence that they know.
  Amanda: Exactly.
  Julia: To continue on just to finish up with the Lilith, later stories from central European Jewish traditions that touch on Lilith, these stories say that she can transform into a cat and can charm victims, which is similar to the modern interpretation that we see in media of the glamor, the vampire glamor, which is basically mind control in order to subdue victims.
  Amanda: Interesting. There's so much literature about Lilith specifically. I know we could probably have like a whole podcast with like 25 parts about her whole history and also different interpretations.
  Julia: Yes, There's a lot of really interesting stuff about Lilith. I'm going to I put that on the schedule for some time in 2020. I think that would be a lot of fun. Moving on to other parts of the world, Africa has a few vampiric beings though my personal favorite comes from Madagascar. It is known as the Ramanga, and it is a living vampire, meaning it's not undead, it's just a person who desires blood. They are said to drink blood and eaten nail clippings, but only of nobles.
  Amanda: Oh, you got to be discerning.
  Julia: I feel like this movie in particular touches upon that and we could talk a little bit at the end about like blood purity and the drinking of virgin's blood and stuff like that in vampire tradition. I'd love to delve into that a little bit more later. There are several folklore traditions around ghoulish or vampiric entities in Asia as well. In India, there's a story of the vetalas, which are spirits or ghouls that inhabit corpses. They were said to, once they inhabit the corpse, they would hang upside down from trees in cemeteries and cremation grounds, so like a bat.
  Julia: Then in Northern India there is the Brahma Rakshasa, which is a creature with a head that was encircled by an intestines and then a skull that would drink the blood of humans. Some good body horror in there. Perfect. Love it. Speaking of body horror, a popular vampiric characteristic in Asia is the ability to detach parts of their upper body. So, shout out to the Philippines for two versions of, depending on what the association is and where the story's coming from. Typically, they are associated with the Aswang. It is the Mandurugo, which means blood sucker and Manananggal meaning the self-segmenter.
  Amanda: Ooh, that is so bad and good.
  Julia: These creatures are said to be a form of our good buddy Aswang. They are said to appear as an attractive woman by day, and at night develop wings and a probiscus like tongue that was used to feed off of fetuses in pregnant women's wombs. When they develop those wings, they would separate their upper torso from their legs and just fly around like that.
  Amanda: Yikes. I love it. God. Shout out Filipino Spirits listener base, you are so proud and vocal.
  Julia: Interestingly enough, they're also known to eat entrails, and weirdly enough, the phlegm of sick people.
  Amanda: Okay, go for it.`,
  `Julia: Yeah, I hope that one's helpful in a way. It's like you go to sleep with a stuffy nose and then you wake up with no stuff no stuffy nose. You're like, thanks bud.  
  Amanda: Would you, Julia, if you were coming down with a cold, allow a probiscus like tongue into your nose while you slept to take out all the sickness, but then you're not sick anymore.  
  Julia: I was going to say, if I was asleep, I would have no problem with it.  
  Amanda: Yeah. No, I think awake is a step too far, but ...  
  Julia: No, if I have to watch it happen, I don't think so.  
  Amanda: One sleeping. Go for it.  
  Julia: Go for it. Moving on from the Philippines, the Jiangshi from China, they're not typically what we would classically think of as vampires. They're corpses that are reanimated through magical means, usually in order to return a body to the family if they were to die elsewhere. Again, talking about like the importance of where the body is buried and burial practice in particular. A sorcerer would be hired by a family in order to reanimate the corpse with a piece of spell paper, which was then attached to their forehead. One of the most interesting aspects of the Jiangshi to me is because of rigor mortis. It's doesn't say explicitly because of rigor mortis in the story, but typically because of rigor mortis, the Jiangshi are only able to move around via hopping.  
  Julia: So, they would hop after the sorcerer as they led them back to the estate. However, if the spell paper were to be removed, either accidentally or if the sorcerer was unhappy because he wasn't being paid properly for his services, the Jiangshi would become dangerous and would go about killing the living and absorbing their life essence.  
  Amanda: I was going to say it reminded me a little bit of golem with the word on the forehead, bringing them to life, but taking away a golem's word or erasing it, just de-animates them, versus makes them uncontrollable or evil.  
  Julia: This brings up an interesting point too, because if we look at, say Frankenstein, as a golem equivalent or a play on that story, the fact that once the Frankenstein's monster is rebuffed by his creator, he becomes violent and goes into a rage basically. It's very similar to the Jiangshi in that way.  
  Amanda: I know. If you haven't read Frankenstein by Mary Shelley, really give it a go. It's very short, and it's one of those classics where I was like, "Oh, I get why this is important now." It is so much more nuanced and interesting than the patients that I'd seen up to that point. Because yeah, the creature doesn't just lash out and arbitrarily decide to become chaotic. He's rejected and hurt, and that to me is such a more compelling reason for what looks from the outside like monster's behavior.  
  Julia: I also think, and not to go off track about Frankenstein's monster, I also really liked the idea of even if the creature wasn't rebuffed by Dr. Frankenstein who isn't a doctor, he's a grad student basically, even if he wasn't rebuffed, the horror of being born again, I feel would be enough to drive a person to lash out. Just because the horror of ... and again, this is going back to the vampire idea where we finally have to in-depth, we finally don't have to have these needs met and we can finally rest, and to be brought back from that rest back into the world of the living in literally a violent way. The creature has every reason to lash out.  
  Amanda: Yeah. They definitely depict him as more of a like newborn blank slate, but parts being collected from deceased people. There's absolutely, I think an argument to be made that there is some pent up, either consciousness or suffering or just the body remembers type situation and ooh, that's really interesting.  
  Julia: Anyway, let's finish up a little with some European vampire traditions just because they're probably the most well-known between the two of us. Then we can get to your media stuff after we get a refill.  
  Amanda: Yes, yes, yes.`,
  `Julia: In Albania, the shtriga is a vampiric witch that would feed on the blood of infants and could turn into a flying insect like a moth, a fly or a bee.  
  Amanda: Ooh, that Rita Skeeter ish.  
  Julia: Big mood. In Romania, vampires were known as moroi, and a human could become one if they were ... basically, it was just like there's a bunch of different qualifying factors where like born with a birth defect, like an extra nipple or a tail or extra hair somewhere means that one would be doomed to become a vampire in death. Another one being that if the seventh child of a family, and all of the children were born the same sex, that child would then become a vampire in death. Basically, there's a whole other bunch of like circumstances in pregnancy that basically doom someone to become a vampire to the point where I'm like genuinely surprised that there are not more vampires.  
  Julia: It's just like, well if your mother sees a black cat while she's pregnant with you, you're doomed to become a vampire in death. I'm like, that happens so often. There would be so many vampires.  
  Amanda: It's another example of like how society is so obsessed so policing the pregnant body and making, during pregnancy people act in the most ridiculously capital V virtuous way, and ridiculous.  
  Julia: Romanian vampires are said to bite their victims either over their heart or between the eyes, which makes them unique compared to other vampires. Usually we see the neck biting or going for the main arteries, but I like the idea of between the eyes. It's a really interesting one.  
  Amanda: Yeah. I feel like I've seen over the heart or read about it, but I think that's more just like romantic connotation.  
  Julia: Yes. That's the sexy vampire.  
  Amanda: Listen, right to the source. I respect it.  
  Julia: So, in South Slavic folklore, vampires are said to develop slowly over time. This is my favorite version of the vampire origin story. In the first 40 days of making a vampire, for instance, they appear as a shadow like creature and gradually gained strength as they feed off of people, taking the shape of a jelly-like boneless mass, and then eventually forming into a mirror version of who they were in life.  
  Amanda: So interesting and very Frankensteinian.  
  Julia: I liked that a lot. I just liked the idea of the gooey body. It's so unsexy.  
  Amanda: Same.  
  Julia: There are several ways of identifying vampires across the world. My personal favorite I will tell you is the Romanian version where you put a seven-year-old boy dressed in white on a white horse and then you just let them loose in the graveyard at midday, and then wherever the horse stops to eat, that's where the vampire's grape is.  
  Amanda: Oh no.`,
  `Julia: It's very, very cute. Anyway, and there are various ways to kill vampires depending on where you may find them, and this list was compiled by an article on Thought Catalog. You can burn it. You can bury the corpse face down. You could drive a wooden stake through its heart. You can pile stones on the grave. You can put poppy seeds or wild roses on the grave. You can boil the head in vinegar. You can place a coin in its mouth.  
  Amanda: Pickle a vampire head, no thank you.  
  Julia: You can place a coin in its mouth and decapitate it with an ax. You can put a lemon in its mouth. You could bury it at a crossroads. You could remove the heart and cut it in two, you can put garlic in the mouth and drive a nail through the temple. You can cut off the toes and drive a nail through the neck and you can pour boiling oil on the body and then drive a nail through the navel.  
  Amanda: Yikes. So many references to like pickling and roasting, but also violence.  
  Julia: A lot of cooking going on of the vampires. I'm not sure how I feel about that.  
  Amanda: Maybe it is because I have been trying to perfect my roast chicken technique, but I'm like, "Oh yes, no lemon in the cavity. That's great."  
  Julia: Of course, a little bit of garlic in there too, and then you put an ax through its temple.  
  Amanda: Oh no.  
  Julia: It's not that far off from a roast chicken. You're absolutely right.  
  Amanda: It's really not.  
  Julia: Boiling the head and vinegar, also probably pretty delicious.  
  Amanda: Yeah, or ways that you mainly kill shellfish before boiling them. Stuff like that.  
  Julia: Well, Amanda, that's my brief overview of vampires. Again, I'm sure we could do a whole series on different vampire lore from different parts across the world, but we just wanted to touch base on this since it applied to Only Lovers Left Alive.  
  Amanda: Totally. Well, I am delighted to tell you about the vampire media that I found, but first, why don't we grab a refill of this delicious cocktail.  
  Julia: Let's go get some aviations.  
  Amanda: Julia, we are sponsored this week by Calm, and as you know, especially when traveling, it is hard to find those moments of relaxation and peace and not thinking about where you're going to go next or if you're on time for staff or where are you going to find a good meal. I really enjoy using Calm to keep myself centered while I'm traveling as I am today when this episode comes out. Calm is the number one app for sleep, relaxation and meditation. They have of course, those famous sleep stories, which are bedtime stories for adults, including a new iconic voice like LeVar Burton and Nick Offerman narrating some of the stories.  
  Julia: I love Nick Offerman.`,
  `Amanda: I know. Jake can't read you a bedtime story. Fair enough. Nick Offerman can.  
  Julia: Incredible.  
  Amanda: They've also soothing music from artists like Sam Smith. There are guided meditations, breathing exercises, and a lot more to help you relax and distress, and at calm.com/spirits, you can get a limited time offer of 40% off a Calm premium subscription, that includes hundreds of hours of programming, unlimited all available to you in Calm premium.  
  Julia: Yeah, over 60 million people use Calm and you can join them today by going to calm.com/spirits.  
  Amanda: That's 40% off unlimited access to Calm's entire library with new content added every week, by the way, at calm.com/spirits. Thanks Calm.  
  Julia: We are also sponsored this week by ThirdLove. ThirdLove does bras differently. They believe that everyone deserves to feel comfortable and confident every day, and with the right support, they can help them do this.  
  Amanda: Literally.  
  Julia: Calm has a fit finder quiz that helps people in under 60 seconds with a few simple questions. Find the perfect bra for them. It is there to ask you questions that you didn't know actually determined what bra was the best fit for you, like your breast shape or the styles that best suit that, and the perfect fit promise guarantees that every customer has 60 days to wear it, wash it and put it to the test, and if you don't love it, you can return it, and ThirdLove wash it and then donate it to someone in need. ThirdLove's team of expert fit stylists are dedicated to helping you find that perfect fit. They're always available for chat or by email. Then returns and exchanges are always free and easy.  
  Amanda: Which I appreciated because I was able to try a couple of different styles, and if you are kind of wondering what size is best for you or whether a certain cut will work with the clothes you wear, it's really easy and free to do that return.  
  Julia: Yeah, so ThirdLove knows that there is a perfect bra for everyone. Right now, they're offering our listeners 15% off their first order by going to thirdlove.com/spirits to find your perfect fitting bra.  
  Amanda: That's 15% off your first purchase at thirdlove.com/spirits. Finally, we are sponsored this week by Tab for a Cause. This is one of my favorite, fastest, easiest ways to support causes that I believe in while just browsing the web. It's a browser extension, so you can install it on Chrome or Firefox, whatever browser you're using. Every time you open up a new tab, it shows you a pretty picture with an ad at the bottom. Revenue from that ad goes to charity. You can join team Spirits and help us see how much money the conspirators can raise for charity at tabforacause.org/spirits.  
  Julia: Thanks Tab for a Cause.  
  Amanda: Thanks. You're helping me have a little moment of peace and also raise money for charity. That's tabforacause.org/spirits. So, Julia, let me walk you please through a timeline of vampire books, movies, manga and TV shows throughout the ages.  
  Julia: You got me some vampire manga, man, you shouldn't have.`,
  `Amanda: I did. I know it was very exciting. I was going to say these mostly focus on like a Western European and North American depictions of vampires, but I do think we have a fairly decent spread, but if there are some vampire media that you love, that you would love for us to check out, feel free to let us know. The oldest reference that I could find apart from the poem that you mentioned at the top is a book called The Bride of Corinth by my homeboy Johann Wolfgang von Goethe. Goethe published this poem, The Bride of Corinth in 1797, and the most ... if you don't know who Goethe is, it doesn't matter. He's an extremely dramatic German writer. My favorite and most drama filled lines from this poem are, "From my grave to wander, I am forced still to seek the God's long severed link, still to love the bridegroom I have lost and the lifeblood of his heart to drink."  
  Amanda: This is translated from German I should say, but I love that translation. It is sassy, it is byery. It's wonderful.  
  Julia: Fuck me up. That is good.  
  Amanda: I know. I also liked, which I haven't really seen before, this link between a love that you had when mortal and drinking that specific person's blood. If we fast forward about a century, that brings us of course to the daddy of all English language vampire literature.  
  Julia: He is the daddy of it, isn't he?  
  Amanda: It's Dracula. Now, this book, which I haven't read before, I didn't realize was told in epistolary format. That means that it's told as a series of letters, diary entries, newspaper articles and ships log entries.  
  Julia: It is very good. It's like the first audio fiction podcast needs a conceit to it.  
  Amanda: It's like a scrapbook. It's extremely good.  
  Julia: Amanda, have you sat down and watched the new Dracula show on Netflix?  
  Amanda: Not yet.  
  Julia: Written by Steven Moffat and Mark Gatiss.
  Amanda: I'm a little burned out to be honest on Moffat, but I'll consider it.
  Julia: I will say the first two episodes very good. Last one, not my favorite.`,
  `Amanda: So, do they play with or reference this like meta textual element of being told from different media?  
  Julia: They do in the first episode, because the implication is that Jonathan Harker has written his account of what happened while he was in Castle Dracula.  
  Amanda: Interesting.  
  Julia: Yes, and it's being read by some nuns that found him.  
  Amanda: Interesting. The castle, like you mentioned, does play a big part in the novel. Just a couple of other interesting elements I found. So, the novel takes place like chronologically, first of all, and largely in England and also Transylvania, of course, within the same year between May and November. Then there's a short note at the end of the final chapter that's written seven years after the events outlined in the novel, which I thought was funny because seven is such a cult number.  
  Julia: Also, the seventh child, if they're all the same, be destined to become a vampire.  
  Amanda: Also, a question for you. So, Dracula buys property in the book under the name Count De Ville, is Cruella a vampire, yes or no?  
  Julia: The answer that popped into my head is yes, but only drinks Dalmatian blood.  
  Amanda: Maybe so, I don't know. I can say I thought it was very funny. There are also a lot of elements of course of the things we associate now with like canonical vampire texts. There is garlic, a doctor who is treating like a victim of Dracula's. They know that she's experiencing blood loss, which to their credit, I don't know if I could have diagnosed, just seeing a pale person who's cold all the time, but they prescribe garlic specifically as a palliative for the blood loss, specifically "garlic flower should be placed throughout her room and weave a necklace of withered garlic blossoms for her to wear." So very, in my mind, Ophelia vibes of just being covered with dried flowers as you go to your eventual doom.  
  Julia: You know what? I just Googled something. Garlic is said to accelerate red blood cell turnover, which might have something to do with the idea that like feed garlic to a victim or someone who is suffering from either anemia or blood loss.  
  Amanda: Oh yeah. I know for sure there are definitely health benefits to garlic and to their credit, they knew what to prescribe but that was really interesting so it's not necessarily a vampire repellent. It's just associated with a vampire's victim.  
  Julia: Yeah. We talked about it that a garlic and also a nail through the temple I believe, is the way to destroy a vampire.  
  Amanda: Similarly, to your list of ways to kill a vampire mentioned earlier, there are also a couple other things that people try to prevent either a victim from being turned into a vampire or vampires from moving. Crosses are placed over deceased woman's mouth to delay her conversion or hopefully prevent it and sacramental bread is also placed in boxes of grave dirt to prevent Dracula from using them.  
  Julia: Sure. Makes sense. That's actually one of my favorite parts of the novels when they do like ... so Dracula has a bunch of houses where he has his caskets full of dirt where he can go and hang out, and they do a raid on all of the places that they know he's located in and that's how they make sure that he can't sleep there.  
  Amanda: Nice. They also eventually kill Dracula by cutting him through the throat with a knife while at the same time, a mortally wounded Quincy, it's supporting character, stabs the count in the heart with a Bowie knife. Dracula then crumbles to dust, which again we see very often in successive vampire media, and his victim Mina is freed from her curse of vampirism as the scar on her forehead disappears. There have definitely been other examples where if the sire is killed, then either other vampires are let go of some thrall, but I don't think I've seen their vampirism reversed that all.  
  Julia: Yeah, no, that typically is not the case I believe. Typically, they would also just be let go of their curse or something to that effect. I guess if perhaps if the transformation is not fully occurred, if you're not in the goose, or if you are still in the goose state, they won't be fully transformed or what-have-you.  
  Amanda: Totally. As you no doubt remember, at the end of the day, the castle is destroyed. There's actually a fragment of tag I found at the Wikipedia page that was removed from the original manuscript but quoted here, which I just thought it was a really wonderful invitation for us to think about why we like horror. This goes, "From where we stood. It seemed as though the once fierce volcano burst had satisfied the need of nature and that the castle and the structure of the hill had sunk again into the void. We were so appalled with the suddenness and the grander that we forgot to think of ourselves."  
  Julia: Interesting.`,
  `Amanda: That to me is like, we see a spectacle, we see something unexpected and a little horrifying. It's not just because we're gluttons for punishment and want to make ourselves suffer, but it's because it takes us out of ourselves, and just like the sublime, the literary concept of the sublime is something that awes and terrifies you so much that you feel not like an individual but like a part of a bigger universe. I think that's what a lot of horror does for us.  
  Julia: Yeah. No, I absolutely agree. I love the examination of horror in particular. We need to read more academic papers on horror.  
  Amanda: Definitely. Just a couple of fun facts to close out this Dracula book chapter. You might ask Julia, why have there been so many adaptations of Dracula? Why is it this specific story that becomes the archetypal vampire? Well, it's because Bram Stoker fucked up his copyright. It was copyrighted in the US in 1899 when Doubleday published the novel. But when Universal Studios then purchased the rights to the book to make it to the film, they discovered that Bram Stoker had not actually complied with a correct portion of the law, which meant the novel was placed into public domain.  
  Julia: It's so funny and so dumb. I love it.  
  Amanda: As a final little humanizing factoid, people obviously throughout Bram Stoker's life were like, "Where'd you get this idea? Where did this come from?" At some point, he started claiming that he had had a nightmare caused by eating too much crab meat about a vampire king rising from his grave.  
  Julia: Hey Bram Stoker, what the fuck?  
  Amanda: I didn't know that crabs were the most occult food.  
  Julia: Apparently. Something about shellfish.  
  Amanda: Extremely good. We move then into the film era, and there of course is an eponymous Dracula film in 1931, which I will get to, but there were a couple before that as well, which really surprised me. Starting with an American silent film directed by Robert G. Vignola called The Vampire in 1913. This one was based on an eponymous poem by Rudyard Kipling, who's a horrible racist. It stars Alice Hollister and Harry F. Millarde. This is interesting because it's the first film that people cite as depicting a vamp character, also known as the femme fatale, which I hadn't really tied those two things together, but the deadly sexy woman was known for a time as a vamp.  
  Julia: Ooh, interesting. I didn't know that. I'm surprised that I didn't know that.  
  Amanda: Yeah. In the film, it's actually interesting too, because media is referenced in the film itself. The main character moved to the city for a new job. He meets an adventuress, which sounds like a great title named Sybil.  
  Julia: I'm putting those on business cards.  
  Amanda: Oh yeah. Of course, in the sort of sexist plot here, Sybil makes Harry forget about his fiancé, Helen, but in fact, Sybil is a vampire who's going to ruin his life. He loses his job, becomes an alcoholic, Sybil abandons him. Then Harold goes to the theater and watches the "Vampire Dance," which itself depicts a man dominated by a beautiful woman who eventually takes his life by putting a bite on him. Harold uses this, I guess as a way to understand his own failings.  
  Julia: He's, "Oh shit, that's me."  
  Amanda: Yeah, and tries to redeem himself. So many layers here.  
  Julia: There's a lot going on there-  
  Amanda: I'm here, nine years later in Germany, of course we get Nosferatu: A Symphony of Horror.  
  Julia: Still, one of the best vampire films to date.  
  Amanda: It is. It is a silent German expressionists horror film. In fact, it almost didn't become a thing that we know about because Bram Stoker's errors sued the film team over this adaptation. It was an adaptation of a Dracula and a court ordered all copies of the film destroyed, but a few prints survived and that is how the film was preserved and can be regarded as a masterpiece of cinema.`,
  `Julia: Bravo, Bravo, good job underground network of film lovers, proud of you.  
  Amanda: Incredible. There is a lot of kind of changes from the novel. So like vampire is replaced with the word Nosferatu, and Count Dracula is renamed Count Orlok.  
  Julia: Oh God, that shadow of him climbing the staircase it's one of my favorite shots of all time.  
  Amanda: Yeah, it really is.  
  Julia: It is presented as a possibly archaic Romanian words synonymous with vampire. However, it was largely popularized because of that film. Seems like it probably comes from a Romanian word that means offensive or troublesome.  
  Amanda: Well, there you go.  
  Julia: There we go.  
  Amanda: I think that's definitely true because the film focuses on how the townsfolk around Orlok, like townsfolk are just dying, and unlike Dracula, he is not turning them into other vampires, but just killing the victims. Orlok also would be killed by sunlight versus the original Dracula is only weakened by sunlight.  
  Julia: Interesting.  
  Amanda: Yeah, it's definitely seen as like an important stepping stone in cinema. It also is definitely ... trades in antisemitic stereotypes and is not perfect in any way, but it is an influential piece of how future directors and creators thought about vampires.  
  Julia: It's really interesting too because in a lot of the research that I did about historic vampires and vampire traditions and stuff like that, the use of sunlight as a deterrent or killer for vampires is not like super common. Like much like many creatures that we see in folklore and mythology, they tend to hunt at night or only come out at night because that's when people are vulnerable or sleeping. But there's very little that implies that vampires are killed by sunlight or weakened by sunlight.  
  Amanda: That's really interesting.  
  Julia: Yeah.`,
  `Amanda: So just to close out the Nosferatu legacy, it was remade in 1979 by Verner Herzog, you might know from so many iconic films, which I thought was hilarious because I never knew that. It is set in 18th century Wismar, Germany in Transylvania, and it is definitely a stylized when we make of the 1922 version. There's also Shadow of the Vampire, the film from the year 2000, which is a meta fiction horror film written by Steven Katz starring John Malcovich and Willem Dafoe. It's a fictionalized documentary about making Nosferatu, which posits that the lead actor is in fact of empire.  
  Julia: I feel like Willem Defoe was made to partake in vampire like media.  
  Amanda: Me too, and he was nominated for best supporting actors.  
  Julia: I'm not surprised. I love Willem Defoe. What a good character.  
  Amanda: Me too. I'm also going to touch on some modern ones that I really enjoy, but in the intervening years, a lot of just wild vampire related stuff. In 1948, Abbott and Costello meet Frankenstein was part of several films where Universal trots out their IP and has Abbott and Costello meet people like Count Dracula, Frankenstein's monster, the Wolf Man, etc.  
  Julia: Makes sense.  
  Amanda: There is Blacula in 1972, part of the blaxploitation horror film movement directed by William Crane. There was also a 1970s Broadway production called Just Dracula, which I saw referenced mostly because Edward Gorey, who is like an iconic illustrator and book cover designer design sets for it, starting in Nantucket and then when all the way to Broadway, and I'll include a link in the Patreon director's commentary because they're absolutely beautiful. It's like a hand painted rendering of the catacombs in Paris, including like these huge arched ceilings. It is just absolutely beautiful and creepy.  
  Julia: Love it. Sounds incredible.  
  Amanda: Then moving into more modern vampire media, I was really interested in where this idea of the vampire Hunter came from, and I'm sure again, that could be a research paper of its own, but I found a few interesting examples. There are some novels in 1983 beginnings when they were published, Vampire Hunter D, where this titular character D wanders through a post nuclear earth, and there's lots of Western elements, science fiction, horror, high fantasy. There's like a thing called the nobility, vampires who planned for possible nuclear war and hoarded and sequestered all resources needed to rebuild and then they like rebuilt post nuclear horror, a like big society of vampires only.  
  Julia: Man, the 80s really fucked us up.  
  Amanda: Really did, Julia.  
  Julia:  The threat of nuclear war, just like everything.  
  Amanda: Really did. In the Manga series, vampire princess Miyu, I started in 1988, the protagonist is stranded in the space between the human world and the demon underworld, and Japanese vampire girl named Miyu is both the daughter of a human being and Shinma, which is a name for a race of "god-demon." So she's born by a vampire and now she has to turn all of the evil demons away. She wants to return to that darkness herself, but not until she is banished all the other Shinma from earth.  
  Julia: Fun fact. Japan didn't really have a vampire tradition or folklore until the 1950s.  
  Amanda: Really?  
  Julia: Yeah. It's one of the few places that didn't really like develop one on its own. The closest that you can find is the Nure-onna. It's a snake woman who drinks the blood of people, but that's what snakes do.  
  Amanda: Fascinating. Well, there are a bunch of other interesting manga and anime series. One of my favorites, there's Chibi Vampire from 2005.  
  Julia: Obviously.`,
  `Amanda: Yep. Unusual vampire girl who instead of drinking blood has to inject into others because she produces too much.  
  Julia: That's adorable. What a cute twist.  
  Amanda: Yeah. There is Blood+, an anime series started in 2005 which is where the protagonist, Saya Otonashi has been living the life of an anemic amnesiac, which is incredible.  
  Julia: This is very good.  
  Amanda: Yep. Then bat like creature attacks her and shatters her normal human existence and feeds on the bat. Saya learns that she's the only one who can defeat them as her blood causes their bodies to crystallize and shatter.  
  Julia: I love a good magic girl with a twist.  
  Amanda: Yep. Me too. Then of course there are a series that we grew up with. There is Buffy the Vampire Slayer. I can't not say it. There's Angel, which also focuses, as it's been off series on the realities of being a vampire in daily life. There's Twilight, which is its own version with its own kind of mythologies and mixes up all kinds of things in that old wonder. I don't know. I didn't want to focus really on those since I know them very well and I think there's a lot of info and more of the audience will be familiar with it. But just running through lists of vampire adaptations, there's just so many things.  
  Amanda: There's a video game called Night Walker, the Midnight Detective from 2001. There's just so many versions of interesting vampire lore. But again, just the bigger takeaways that I got from reading through all of these materials is that vampires are usually either dominant parts of society through being like old and rich or in that, like I mentioned, post-apocalyptic situation, or demons to be hunted. Generally, for story purposes, in a lot of these, there's a vampire that's good. Either they are half vampire, they're cursed with a soul, like an angel. They pledge to fight beside the forces of good, they're in love maybe with the fighter and there is a reason why we have the vampire that's the exception.  
  Julia: Yeah, I'm going to name a couple more just so people aren't like, "How did you not mention blah, blah, blah." Anne Rice's interview with a vampire series True Blood and the novels that those are based off of. Actually, to your point before, Amanda, you were like, "I wonder where the original vampire hunter came from." One could argue that the original vampire Hunter comes from Dracula's Van Helsing.  
  Amanda: Interesting.  
  Julia: Dr. Van Helsing, the like expert that they go to in order to be like, "Hey man, what the fuck? What's going on? How do we kill these vampires?  
  Amanda: Excuse me.  
  Julia: Van Helsing is like, "I am old and I think German."  
  Amanda: That's awesome. There's also Being Human, which is one of my favorite underground adaptations. I haven't gotten into Vampire Diaries but we can.  
  Julia: Yeah, I want to preface this being like, we have probably heard of the vampire thing that you are excited about. I promise we probably have, you don't need to make a recommendation. We've probably heard of it.  
  Amanda: Yes. It's definitely, I know people are excited to tell us about things, but it gets overwhelming when we have dozens and dozens of those. But instead, why don't you pick your favorite vampire thing and share it with a friend and have them listen to the episode. You guys can get on the same page mythology wise, and then together, you can enjoy your favorite thing and talk about the similarities and differences.  
  Julia: Yeah, absolutely. Like I said earlier on in the episode, vampires are wide reaching. There's a lot of different stories. There's a lot of different traditions we didn't talk about in this episode, but we hope that you found it interesting and we hope that you enjoyed Only Lovers Left Alive.  
  Amanda: Well put Julia, and listeners remember ...  
  Julia: Stay creepy.  
  Amanda: Stay cool.  
  Julia:  Watch out.`
];

exports.transcripts = transcripts;